spring:
  datasource:
    url: jdbc:mysql://172.21.233.33:3306/db_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  config-location: classpath:MyBatisConfig.xml
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      yn:
        mybatisintegrationdemo:
          dao: debug
